name: Build APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: false
      - name: Install dependencies
        run: |
          flutter pub upgrade
          flutter clean
          flutter pub get

      - name: Build APK
        run: flutter build apk --release

        with:
          name: mafia-game-apk
          path: build/app/outputs/flutter-apk/app-release.apk
